version: '2'
services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    hostname: gitlab
    restart: unless-stopped
    expose:
      - 80
      - 22
    volumes:
      - ./volumes/gitlab_volume/config:/etc/gitlab
      - ./volumes/gitlab_volume/logs:/var/log/gitlab
      - ./volumes/gitlab_volume/data:/var/opt/gitlab
    mem_limit: 4000m
    memswap_limit: 8000m
    cpu_shares: 512
    cpuset: 0,1

  jenkins:
    build:
      context: images/jenkins/
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    container_name: jenkins
    restart: unless-stopped
    environment:
        JAVA_OPTS: "-Djava.awt.headless=true"
        JENKINS_OPTS: "--prefix=/jenkins"
    expose:
      - 8080
    links:
      - gitlab
      - artifactory
      - tomcat
    volumes:
      - ./volumes/jenkins_volume:/var/jenkins_home
    mem_limit: 3000m
    memswap_limit: 6000m

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss
    container_name: artifactory
    expose:
     - 8081
    volumes:
     - ./volumes/artifactory_volume:/var/opt/jfrog/artifactory
    restart: unless-stopped
    mem_limit: 3000m
    memswap_limit: 6000m
    cpu_shares: 512
    cpuset: 2,3

  tomcat:
    build:
      context: images/tomcat/
    container_name: tomcat
    expose:
     - 8080
     - 22
    volumes:
     - ./volumes/tomcat_volume:/usr/local/tomcat/webapps
    restart: unless-stopped
    mem_limit: 3000m
    memswap_limit: 6000m

  proxy:
    image: nginx
    container_name: nginx_proxy
    restart: unless-stopped
    links:
        - gitlab:gitlab
        - jenkins:jenkins
        - artifactory:artifactory
        - tomcat:tomcat
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./volumes/nginx_volume/conf/nginx.conf:/etc/nginx/conf.d/default.conf.template:ro
        - ./volumes/nginx_volume/certificates:/etc/nginx/certificates
    environment:
        "SSL_CERTIFICATE_NAME": certificate
    command: /bin/bash -c "envsubst '$${SSL_CERTIFICATE_NAME}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    mem_limit: 256m
    memswap_limit: 512m